import { addDoc, collection } from 'firebase/firestore';
import { db } from '../firebase.js';

const bulkIngredients = [
   // 🟡 MISC
  { name: "rice", unit: "grams", category: "misc" },
  { name: "flour", unit: "grams", category: "misc" },
  { name: "sugar", unit: "grams", category: "misc" },
  { name: "salt", unit: "teaspoons", category: "misc" },
  { name: "yeast", unit: "grams", category: "misc" },
  { name: "baking soda", unit: "teaspoons", category: "misc" },
  { name: "vanilla extract", unit: "ml", category: "misc" },
  { name: "egg", unit: "pieces", category: "misc" },
  { name: "noodles", unit: "grams", category: "misc" },
  { name: "breadcrumbs", unit: "grams", category: "misc" },

  // 🟢 FRUIT AND VEG
  { name: "onion", unit: "pieces", category: "fruit and veg" },
  { name: "garlic", unit: "cloves", category: "fruit and veg" },
  { name: "carrot", unit: "pieces", category: "fruit and veg" },
  { name: "potato", unit: "pieces", category: "fruit and veg" },
  { name: "tomato", unit: "pieces", category: "fruit and veg" },
  { name: "cucumber", unit: "pieces", category: "fruit and veg" },
  { name: "apple", unit: "pieces", category: "fruit and veg" },
  { name: "banana", unit: "pieces", category: "fruit and veg" },
  { name: "ginger", unit: "grams", category: "fruit and veg" },
  { name: "bok choy", unit: "grams", category: "fruit and veg" },
  { name: "cabbage", unit: "grams", category: "fruit and veg" },
  { name: "spinach", unit: "grams", category: "fruit and veg" },
  { name: "spring onion", unit: "grams", category: "fruit and veg" },
  { name: "chili pepper", unit: "pieces", category: "fruit and veg" },

  // 🟤 CONDIMENT
  { name: "soy sauce", unit: "ml", category: "condiment" },
  { name: "vinegar", unit: "ml", category: "condiment" },
  { name: "mustard", unit: "ml", category: "condiment" },
  { name: "ketchup", unit: "ml", category: "condiment" },
  { name: "mayonnaise", unit: "ml", category: "condiment" },
  { name: "hot sauce", unit: "ml", category: "condiment" },
  { name: "oyster sauce", unit: "ml", category: "condiment" },
  { name: "fish sauce", unit: "ml", category: "condiment" },
  { name: "hoisin sauce", unit: "ml", category: "condiment" },
  { name: "black bean paste", unit: "grams", category: "condiment" },
  { name: "chili oil", unit: "ml", category: "condiment" },

  // 🔵 SNACK
  { name: "chips", unit: "grams", category: "snack" },
  { name: "pretzels", unit: "grams", category: "snack" },
  { name: "crackers", unit: "grams", category: "snack" },
  { name: "rice cakes", unit: "pieces", category: "snack" },
  { name: "popcorn", unit: "grams", category: "snack" },
  { name: "peanuts", unit: "grams", category: "snack" },
  { name: "trail mix", unit: "grams", category: "snack" },
  { name: "dried fruit", unit: "grams", category: "snack" },
  { name: "chocolate bar", unit: "pieces", category: "snack" },
  { name: "biscuits", unit: "pieces", category: "snack" },

  // 🔴 CHILLED
  { name: "milk", unit: "ml", category: "chilled" },
  { name: "butter", unit: "grams", category: "chilled" },
  { name: "cheese", unit: "grams", category: "chilled" },
  { name: "cream", unit: "ml", category: "chilled" },
  { name: "yogurt", unit: "ml", category: "chilled" },
  { name: "sour cream", unit: "ml", category: "chilled" },
  { name: "tofu", unit: "grams", category: "chilled" },
  { name: "ham", unit: "grams", category: "chilled" },
  { name: "salami", unit: "grams", category: "chilled" },
  { name: "smoked salmon", unit: "grams", category: "chilled" },
{ name: 'Onion', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Garlic', unit: 'cloves', category: 'fruit and veg' },
  { name: 'Carrot', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Bell Pepper', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Tomato', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Cucumber', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Potato', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Sweet Potato', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Cabbage', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Spinach', unit: 'g', category: 'fruit and veg' },
  { name: 'Broccoli', unit: 'g', category: 'fruit and veg' },
  { name: 'Cauliflower', unit: 'g', category: 'fruit and veg' },
  { name: 'Green Beans', unit: 'g', category: 'fruit and veg' },
  { name: 'Peas', unit: 'g', category: 'fruit and veg' },
  { name: 'Mushrooms', unit: 'g', category: 'fruit and veg' },
  { name: 'Leek', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Zucchini', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Eggplant', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Chili Pepper', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Ginger', unit: 'g', category: 'fruit and veg' },
  { name: 'Spring Onion', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Bok Choy', unit: 'g', category: 'fruit and veg' },
  { name: 'Pak Choi', unit: 'g', category: 'fruit and veg' },
  { name: 'Kale', unit: 'g', category: 'fruit and veg' },
  { name: 'Lettuce', unit: 'g', category: 'fruit and veg' },
  { name: 'Celery', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Radish', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Turnip', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Parsnip', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Beetroot', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Corn', unit: 'g', category: 'fruit and veg' },
  { name: 'Asparagus', unit: 'g', category: 'fruit and veg' },
  { name: 'Artichoke', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Avocado', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Apple', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Pear', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Banana', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Orange', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Lemon', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Lime', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Grapes', unit: 'g', category: 'fruit and veg' },
  { name: 'Strawberries', unit: 'g', category: 'fruit and veg' },
  { name: 'Blueberries', unit: 'g', category: 'fruit and veg' },
  { name: 'Raspberries', unit: 'g', category: 'fruit and veg' },
  { name: 'Cherries', unit: 'g', category: 'fruit and veg' },
  { name: 'Peach', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Plum', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Pineapple', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Mango', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Papaya', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Melon', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Watermelon', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Kiwi', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Passion Fruit', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Pomegranate', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Fig', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Date', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Apricot', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Nectarine', unit: 'pcs', category: 'fruit and veg' },
  { name: 'Blackberries', unit: 'g', category: 'fruit and veg' },
  { name: 'Gooseberries', unit: 'g', category: 'fruit and veg' },
  { name: 'Rhubarb', unit: 'g', category: 'fruit and veg' },
  { name: 'Cranberries', unit: 'g', category: 'fruit and veg' },
  { name: 'Currants', unit: 'g', category: 'fruit and veg' },
  { name: 'Olives', unit: 'g', category: 'fruit and veg' },
  { name: 'Sun-dried Tomatoes', unit: 'g', category: 'fruit and veg' },
  { name: 'Pickles', unit: 'g', category: 'fruit and veg' },
  { name: 'Sauerkraut', unit: 'g', category: 'fruit and veg' },
  { name: 'Kimchi', unit: 'g', category: 'fruit and veg' },
{ name: 'Salt', unit: 'g', category: 'condiment' },
  { name: 'Black Pepper', unit: 'g', category: 'condiment' },
  { name: 'White Pepper', unit: 'g', category: 'condiment' },
  { name: 'Paprika', unit: 'g', category: 'condiment' },
  { name: 'Chili Powder', unit: 'g', category: 'condiment' },
  { name: 'Cumin', unit: 'g', category: 'condiment' },
  { name: 'Coriander', unit: 'g', category: 'condiment' },
  { name: 'Turmeric', unit: 'g', category: 'condiment' },
  { name: 'Cinnamon', unit: 'g', category: 'condiment' },
  { name: 'Nutmeg', unit: 'g', category: 'condiment' },
  { name: 'Cloves', unit: 'g', category: 'condiment' },
  { name: 'Allspice', unit: 'g', category: 'condiment' },
  { name: 'Bay Leaves', unit: 'pcs', category: 'condiment' },
  { name: 'Oregano', unit: 'g', category: 'condiment' },
  { name: 'Thyme', unit: 'g', category: 'condiment' },
  { name: 'Rosemary', unit: 'g', category: 'condiment' },
  { name: 'Basil', unit: 'g', category: 'condiment' },
  { name: 'Parsley', unit: 'g', category: 'condiment' },
  { name: 'Dill', unit: 'g', category: 'condiment' },
  { name: 'Chives', unit: 'g', category: 'condiment' },
  { name: 'Sage', unit: 'g', category: 'condiment' },
  { name: 'Tarragon', unit: 'g', category: 'condiment' },
  { name: 'Marjoram', unit: 'g', category: 'condiment' },
  { name: 'Mint', unit: 'g', category: 'condiment' },
  { name: 'Lemongrass', unit: 'g', category: 'condiment' },
  { name: 'Soy Sauce', unit: 'ml', category: 'condiment' },
  { name: 'Tamari', unit: 'ml', category: 'condiment' },
  { name: 'Fish Sauce', unit: 'ml', category: 'condiment' },
  { name: 'Oyster Sauce', unit: 'ml', category: 'condiment' },
  { name: 'Hoisin Sauce', unit: 'ml', category: 'condiment' },
  { name: 'Teriyaki Sauce', unit: 'ml', category: 'condiment' },
  { name: 'Worcestershire Sauce', unit: 'ml', category: 'condiment' },
  { name: 'Vinegar', unit: 'ml', category: 'condiment' },
  { name: 'Balsamic Vinegar', unit: 'ml', category: 'condiment' },
  { name: 'Apple Cider Vinegar', unit: 'ml', category: 'condiment' },
{ name: 'All-purpose flour', unit: 'grams', category: 'misc' },
  { name: 'Baking powder', unit: 'grams', category: 'misc' },
  { name: 'Baking soda', unit: 'grams', category: 'misc' },
  { name: 'Cornstarch', unit: 'grams', category: 'misc' },
  { name: 'Yeast', unit: 'grams', category: 'misc' },
  { name: 'Rice', unit: 'grams', category: 'misc' },
  { name: 'Pasta', unit: 'grams', category: 'misc' },
  { name: 'Bread crumbs', unit: 'grams', category: 'misc' },
  { name: 'Sugar', unit: 'grams', category: 'misc' },
  { name: 'Brown sugar', unit: 'grams', category: 'misc' },
  { name: 'Honey', unit: 'ml', category: 'misc' },
  { name: 'Maple syrup', unit: 'ml', category: 'misc' },
  { name: 'Olive oil', unit: 'ml', category: 'misc' },
  { name: 'Vegetable oil', unit: 'ml', category: 'misc' },
  { name: 'Sesame oil', unit: 'ml', category: 'misc' },
  { name: 'Soy sauce', unit: 'ml', category: 'misc' },
  { name: 'Vinegar', unit: 'ml', category: 'misc' },
  { name: 'Salt', unit: 'grams', category: 'misc' },
  { name: 'Black pepper', unit: 'grams', category: 'misc' },
  { name: 'Paprika', unit: 'grams', category: 'misc' },
  { name: 'Cumin', unit: 'grams', category: 'misc' },
  { name: 'Coriander', unit: 'grams', category: 'misc' },
  { name: 'Turmeric', unit: 'grams', category: 'misc' },
  { name: 'Cinnamon', unit: 'grams', category: 'misc' },
  { name: 'Nutmeg', unit: 'grams', category: 'misc' },
  { name: 'Cloves', unit: 'grams', category: 'misc' },
  { name: 'Star anise', unit: 'grams', category: 'misc' },
  { name: 'Bay leaves', unit: 'grams', category: 'misc' },
  { name: 'Oregano', unit: 'grams', category: 'misc' },
  { name: 'Thyme', unit: 'grams', category: 'misc' },
  { name: 'Basil', unit: 'grams', category: 'misc' },
  { name: 'Parsley', unit: 'grams', category: 'misc' },
  { name: 'Rosemary', unit: 'grams', category: 'misc' },
  { name: 'Sage', unit: 'grams', category: 'misc' },
  { name: 'Chili flakes', unit: 'grams', category: 'misc' },
  { name: 'Five-spice powder', unit: 'grams', category: 'misc' },
  { name: 'Garam masala', unit: 'grams', category: 'misc' },
  { name: 'Curry powder', unit: 'grams', category: 'misc' },
  { name: 'Mustard seeds', unit: 'grams', category: 'misc' },
  { name: 'Fenugreek', unit: 'grams', category: 'misc' },
  { name: 'Fennel seeds', unit: 'grams', category: 'misc' },
  { name: 'Sichuan peppercorns', unit: 'grams', category: 'misc' },
  { name: 'Dried mushrooms', unit: 'grams', category: 'misc' },
  { name: 'Dried chilies', unit: 'grams', category: 'misc' },
  { name: 'Nori sheets', unit: 'pieces', category: 'misc' },
  { name: 'Wonton wrappers', unit: 'pieces', category: 'misc' },
  { name: 'Rice paper', unit: 'pieces', category: 'misc' },
  { name: 'Tofu', unit: 'grams', category: 'misc' },
  { name: 'Tempeh', unit: 'grams', category: 'misc' },
  { name: 'Seitan', unit: 'grams', category: 'misc' },
  { name: 'Miso paste', unit: 'grams', category: 'misc' },
  { name: 'Tahini', unit: 'grams', category: 'misc' },
  { name: 'Peanut butter', unit: 'grams', category: 'misc' },
  { name: 'Almond butter', unit: 'grams', category: 'misc' },
  { name: 'Coconut milk', unit: 'ml', category: 'misc' },
  { name: 'Evaporated milk', unit: 'ml', category: 'misc' },
  { name: 'Condensed milk', unit: 'ml', category: 'misc' },
  { name: 'Stock cubes', unit: 'pieces', category: 'misc' },
  { name: 'Gelatin', unit: 'grams', category: 'misc' },
  { name: 'Agar agar', unit: 'grams', category: 'misc' },
  { name: 'Pectin', unit: 'grams', category: 'misc' },
  { name: 'Food coloring', unit: 'ml', category: 'misc' },
  { name: 'Vanilla extract', unit: 'ml', category: 'misc' },
  { name: 'Almond extract', unit: 'ml', category: 'misc' },
  { name: 'Lemon extract', unit: 'ml', category: 'misc' },
  { name: 'Orange extract', unit: 'ml', category: 'misc' },
  { name: 'Rose water', unit: 'ml', category: 'misc' },
  { name: 'Orange blossom water', unit: 'ml', category: 'misc' },
  { name: 'Cooking wine', unit: 'ml', category: 'misc' },
  { name: 'Shaoxing wine', unit: 'ml', category: 'misc' },
  { name: 'Mirin', unit: 'ml', category: 'misc' },
  { name: 'Rice vinegar', unit: 'ml', category: 'misc' },
  { name: 'Black vinegar', unit: 'ml', category: 'misc' },
  { name: 'White vinegar', unit: 'ml', category: 'misc' },
  { name: 'Balsamic vinegar', unit: 'ml', category: 'misc' },
  { name: 'Apple cider vinegar', unit: 'ml', category: 'misc' },
  { name: 'Malt vinegar', unit: 'ml', category: 'misc' },
  { name: 'Fish sauce', unit: 'ml', category: 'misc' },
  { name: 'Oyster sauce', unit: 'ml', category: 'misc' },
  { name: 'Hoisin sauce', unit: 'ml', category: 'misc' },
  { name: 'Plum sauce', unit: 'ml', category: 'misc' },
  { name: 'Black bean sauce', unit: 'ml', category: 'misc' },
  { name: 'Chili sauce', unit: 'ml', category: 'misc' },
  { name: 'Sriracha', unit: 'ml', category: 'misc' },
  { name: 'Ketchup', unit: 'ml', category: 'misc' },
  { name: 'Mayonnaise', unit: 'ml', category: 'misc' },
  { name: 'Mustard', unit: 'ml', category: 'misc' },
  { name: 'Barbecue sauce', unit: 'ml', category: 'misc' },
  { name: 'Worcestershire sauce', unit: 'ml', category: 'misc' },
  { name: 'Soy milk', unit: 'ml', category: 'misc' },
  { name: 'Almond milk', unit: 'ml', category: 'misc' },
  { name: 'Oat milk', unit: 'ml', category: 'misc' },
  { name: 'Rice milk', unit: 'ml', category: 'misc' },
  { name: 'Coconut water', unit: 'ml', category: 'misc' },
  { name: 'Sparkling water', unit: 'ml', category: 'misc' },
  { name: 'Tonic water', unit: 'ml', category: 'misc' },
  { name: 'Club soda', unit: 'ml', category: 'misc' },
  { name: 'Ginger ale', unit: 'ml', category: 'misc' },
  { name: 'Cola', unit: 'ml', category: 'misc' },
  { name: 'Lemon-lime soda', unit: 'ml', category: 'misc' },
  { name: 'Root beer', unit: 'ml', category: 'misc' },
  { name: 'Orange soda', unit: 'ml', category: 'misc' },
  { name: 'Grape soda', unit: 'ml', category: 'misc' },
  { name: 'Cream soda', unit: 'ml', category: 'misc' },
  { name: 'Energy drink', unit: 'ml', category: 'misc' },
  { name: 'Sports drink', unit: 'ml', category: 'misc' },
  { name: 'Iced tea', unit: 'ml', category: 'misc' },
  { name: 'Lemonade', unit: 'ml', category: 'misc' },
  { name: 'Fruit punch', unit: 'ml', category: 'misc' },
  { name: 'Apple juice', unit: 'ml', category: 'misc' },
  { name: 'Orange juice', unit: 'ml', category: 'misc' },
  { name: 'Grape juice', unit: 'ml', category: 'misc' },
  { name: 'Cranberry juice', unit: 'ml', category: 'misc' },
  { name: 'Pineapple juice', unit: 'ml', category: 'misc' }
];

bulkIngredients.forEach(async (ingredient) => {
  await addDoc(collection(db, 'ingredients'), ingredient);
});

export default bulkIngredients;